name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  backend:
    name: Backend (Django)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install black flake8 pip-audit

      - name: Run Python lint
        run: |
          source venv/bin/activate
          black --check .
          flake8 .

      - name: Run dependency audit
        run: |
          source venv/bin/activate
          pip-audit

      - name: Run Django tests
        run: |
          source venv/bin/activate
          python manage.py test

  frontend:
    name: Frontend (React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install
          npm install eslint prettier --save-dev

      - name: Run ESLint
        run: |
          npx eslint . --ext .js,.jsx

      - name: Run Prettier
        run: |
          npx prettier --check .

      - name: Run frontend tests
        run: npm test -- --watchAll=false
